### ISSUE TITLE
Support for Deeplab V3 Mobilenet V2

### ISSUE THREAD

**Issue by SanthoshRajendiran** [tantara/JejuNet#1]
Hello. The application you have provided works perfectly awesome with the provided tflite file. We tried the same approach replacing the model, with newer version of deeplab from Tensorflow model zoo(https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md). The inference obtained is, there is difference in the input nodes and output nodes, between their pb and your tflite. Any suggestions or ideas on how to overcome this. Due to the difference, we are getting an issue in the loadmodel function.. Actual error is "ByteBuffer is not a valid flatbuffer model". If you need, we can provide you a Log file for the same. And also do we have to make any changes in the asset variables, if we use the recent tflite?

**Comment by tantara** [comment]
@SanthoshRajendiran the current version of tf/tf-lite doesn't support a part of operations used in DeepLab V3+, especially, preprocessing. I changed unsupported operations and implemented it in java or native tf-lite so that the `.tflite` is slightly different with the original `.pb`. The project was based on tf 1.8.

**Comment by kismeter** [comment]
@tantara would you give some directions on how you  change the ```.tflite```, I noticed that your ```.tflite``` only has 71 operators, the inputs node is ```MobilenetV2/MobilenetV2/input```, not the official ones ```ImageTensor```. Thanks

**Comment by hufangjian** [comment]
hi，could you give me some advise on how to product the MobileNet.tflite,thanks.

**Comment by hufangjian** [comment]
hi，could you give me some advise on how to add ‘RESIZE_BILINEAR‘ ops in tensorflow lite?
the official have not support  'tf.image.resize_bilinear' ops . thanks.

**Comment by tantara** [comment]
@SanthoshRajendiran @kismeter @hufangjian I will post tutorials about how to convert/run deeplabv3+ on tf-lite. Please refer to the posts.

**Comment by tantara** [comment]
@kismeter I skipped some layers on preprocessing due to unsupported ops.

**Comment by tantara** [comment]
@hufangjian I didn't use `tf.image.resize_bilienar` on tf-lite, and implemented it in native java.

**Comment by kismeter** [comment]
@tantara do you have any progress on post tutorials about how to convert/run deeplabv3+ on tf-lite?

**Comment by tantara** [comment]
@kismeter I'm planning to post a series of tutorials in tf 2.0.

**Comment by kismeter** [comment]
@tantara thanks, waiting for your tutorials.

**Comment by normandra** [comment]
bump, also waiting for said tutorials

**Comment by tantara** [comment]
Hi guys, please refer to the official tutorials https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md
