### ISSUE TITLE
How to convert model correctly to Tflite

### ISSUE THREAD

**Issue by abi98213** [tantara/JejuNet#10]
Hello!
I am trying to Convert model ( http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_trainval_2018_01_29.tar.gz ) to tflite. But I don't know what should be input and output shape for this. So kindly tell me how did you converted to tflite.

**Comment by tantara** [comment]
Probably (513, 513, 3), (33, 33, 3) for input and output, respectively
