### ISSUE TITLE
트레이닝 데이터셋 문의

### ISSUE THREAD

**Issue by ilous12** [tantara/JejuNet#2]
딥러닝 초보인데 많은 도움이 되었습니다.

구글 AI 예시 그림처럼, 할려고 하는데, 
혹시 트레이닝을 직접 하신건가요? 트레이닝셋과 트레이닝 방안은 안써져 있네요. 혹시 공유 가능하실까요?

**Comment by tantara** [comment]
학습은 따로 하지 않았고 구글이 제공한 pretrained weights를 사용했습니다. 8bits quantization 모델에서 finetuning했습니다. 데이터셋은 pascal voc 사용했습니다. 구글 AI 예시처럼 사람만 인식하는 네트워트를 만들고싶으시면 person 데이터만 따로 뽑거나 matting 관련한 데이터셋을 쓰시면 될 거 같습니다.

**Comment by ilous12** [comment]
한가지 질문 하나만 드려도 될까요?
Deeplab 직접 트레이닝하고 있는데, frozen.pb를 tflite 로 변활할때보니까. FusedBatchNorm가 SpaceToBatchNd로 변환되는것으로 보이는데, 혹시 SpaceToBatchNd를 제거할수 있는 방법이 있을까요? 

제생각에는 slim에서 제거하면 될것 같은데, 어렵네요.

GPU 모델을 저희 프로젝트에서 사용하기 위해서, 진행중인데, 막히네요 ㅠ

**Comment by ilous12** [comment]
해결했습니다. 감사합니다.
