### ISSUE TITLE
How is model trained and converted?

### ISSUE THREAD

**Issue by haikuoyao** [tantara/JejuNet#3]
How is Deeplab model trained and converted to TF-Lite file?

Thanks.

**Comment by RizanPSTU** [comment]
Please provide the answer. I am requesting

**Comment by tantara** [comment]
@haikuoyao @RizanPSTU Hi guys, please refer to the official tutorials https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md
